In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import warnings
warnings.simplefilter('ignore', FutureWarning)

In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [5]:
len('B. Sc.')

6

In [6]:
'on campus'.replace('on', 'healthy').replace('campus', 'place')

'healthy place'

In [7]:
'working hardly'.replace('working', 'hardly').replace('hardly', 'working')

'working working'

In [9]:
'working hardly'.replace('working', 'potato').replace('hardly', 'working').replace('potato', 'hardly')

'hardly working'

In [10]:
mystring1 = 'There are three kinds of lies: lies, damned lies, and statistics.' 
mystring1.split(',')

['There are three kinds of lies: lies', ' damned lies', ' and statistics.']

In [11]:
mystring1.split(',')[2]

' and statistics.'

In [12]:
mystring1

'There are three kinds of lies: lies, damned lies, and statistics.'

In [13]:
mystring1.split('s')

['There are three kind',
 ' of lie',
 ': lie',
 ', damned lie',
 ', and ',
 'tati',
 'tic',
 '.']

In [14]:
mystring1.split('s')[0][1]

'h'

In [15]:
mystring1.split('s')[0,1]

TypeError: list indices must be integers or slices, not tuple

In [16]:
mystring1

'There are three kinds of lies: lies, damned lies, and statistics.'

In [17]:
mystring1.split(' s ')

['There are three kinds of lies: lies, damned lies, and statistics.']

In [18]:
mystring1.split('s')

['There are three kind',
 ' of lie',
 ': lie',
 ', damned lie',
 ', and ',
 'tati',
 'tic',
 '.']

In [19]:
mystring1.split('s')[0]

'There are three kind'

In [20]:
mystring1.split(s)

NameError: name 's' is not defined

In [21]:
mystring1.split(',')

['There are three kinds of lies: lies', ' damned lies', ' and statistics.']

In [22]:
mystring1.split(',')[0][1]

'h'

In [23]:
mystring1.split(',')[0,1]

TypeError: list indices must be integers or slices, not tuple

In [24]:
mystring1.split(',')[0]mystring1.split(',')[1]

SyntaxError: invalid syntax (<ipython-input-24-e28a9ed9aade>, line 1)

In [25]:
mystring1.split(',')[0].mystring1.split(',')[1]

AttributeError: 'str' object has no attribute 'mystring1'

In [26]:
mystring1.split(',')[0]

'There are three kinds of lies: lies'

In [27]:
mystring1.split(',')[0].[1]

SyntaxError: invalid syntax (<ipython-input-27-8aa522b352b8>, line 1)

In [28]:
mystring1.split(',')[0]
mystring1.split(',')[1]

' damned lies'

In [29]:
mystring1.split(',')[1]

' damned lies'

In [30]:
mystring1.split(',')[0]

'There are three kinds of lies: lies'

In [31]:
1.0 = 1

SyntaxError: cannot assign to literal (<ipython-input-31-2e3aa4df2759>, line 1)

In [32]:
1.0 ==1

True

In [33]:
mystring1.split('lies')

['There are three kinds of ', ': ', ', damned ', ', and statistics.']

In [34]:
mystring1.split('s,')

['There are three kinds of lies: lie', ' damned lie', ' and statistics.']

In [35]:
mystring1

'There are three kinds of lies: lies, damned lies, and statistics.'

In [36]:
mystring1.split(',')

['There are three kinds of lies: lies', ' damned lies', ' and statistics.']

In [37]:
four = 4

In [38]:
root_four = sqrt(four)

NameError: name 'sqrt' is not defined

In [39]:
sqrt(4)

NameError: name 'sqrt' is not defined

In [40]:
sqrt[4]

NameError: name 'sqrt' is not defined

In [41]:
np.sqrt(4)

2.0

In [42]:
np.sqrt(four)

2.0

In [43]:
one_over_root_two = sine_45

NameError: name 'sine_45' is not defined

In [44]:
1\np.sqrt(2)

SyntaxError: unexpected character after line continuation character (<ipython-input-44-7897e68c0909>, line 1)

In [45]:
1/np.sqrt(2)

0.7071067811865475

In [46]:
one_over_root_two = 1/np.sqrt(2)

In [47]:
cosine_45 = cos(45)

NameError: name 'cos' is not defined

In [48]:
cos(180)

NameError: name 'cos' is not defined

In [49]:
math.cos(pi*45/180)

NameError: name 'math' is not defined

In [50]:
math.cos(180)

NameError: name 'math' is not defined

In [51]:
np.cos(180)

-0.5984600690578581

In [52]:
np.cos(pi*45/180)

NameError: name 'pi' is not defined

In [53]:
np.pi

3.141592653589793

In [54]:
np.cos(np.pi*45/180)

0.7071067811865476

In [55]:
one_over_root_two = 1/np.sqrt(2)
cosine_45 = np.cos(np.pi*45/180)

In [56]:
difference = one_over_root_two - cosine_45

In [57]:
print(difference)

-1.1102230246251565e-16


In [58]:
one_over_root_two = 1/np.sqrt(2)
cosine_45 = np.cos(np.pi*45/180)
difference = one_over_root_two - cosine_45
print(difference)

-1.1102230246251565e-16


In [59]:
txt = "welcome to the jungle"

x = txt.split()

print(x)

['welcome', 'to', 'the', 'jungle']


In [60]:
txt.split()

['welcome', 'to', 'the', 'jungle']

In [61]:
txt.split()[1]

'to'

In [62]:
txt.split()[1].txt.split()[0]

AttributeError: 'str' object has no attribute 'txt'

In [63]:
txt.split()[1],txt.split()[0]

('to', 'welcome')

In [64]:
mystring1 = 'There are three kinds of lies: lies, damned lies, and statistics.'

In [65]:
mystring1.split(',')

['There are three kinds of lies: lies', ' damned lies', ' and statistics.']

In [66]:
mystring1.split(s)

NameError: name 's' is not defined

In [67]:
mystring1.split('')

ValueError: empty separator

In [68]:
mystring1.split(',')

['There are three kinds of lies: lies', ' damned lies', ' and statistics.']

In [69]:
mystring1.split('s')

['There are three kind',
 ' of lie',
 ': lie',
 ', damned lie',
 ', and ',
 'tati',
 'tic',
 '.']

In [70]:
mystring1.split()

['There',
 'are',
 'three',
 'kinds',
 'of',
 'lies:',
 'lies,',
 'damned',
 'lies,',
 'and',
 'statistics.']

In [71]:
mystring1.split()[0,1,2,3,4,10]

TypeError: list indices must be integers or slices, not tuple

In [72]:
mystring1.split()[0],[1]

('There', [1])

In [73]:
mystring1.split()[0],mystring1.split()[1],mystring1.split()[2],mystring1.split()[3], mystring1.split()[4], mystring1.split()[10]

('There', 'are', 'three', 'kinds', 'of', 'statistics.')

In [74]:
mystring1.split(',')[2]

' and statistics.'

In [75]:
a=mystring1.split()[0]

'There'

In [76]:
b=mystring1.split()[1]

In [77]:
c=a+b

NameError: name 'a' is not defined

In [78]:
a=mystring1.split()[0]

In [79]:
c=a+b

In [80]:
print(c)

Thereare


In [81]:
print(a, b)

There are


In [82]:
mystring1.split()
a=mystring1.split()[0]
b=mystring1.split()[1]
c=mystring1.split()[2]
d=mystring1.split()[3]
e=mystring1.split()[4]
f=mystring1.split()[10]

In [83]:
mach2 = (a, b, c, d, e, f)

In [84]:
print(mach2)

('There', 'are', 'three', 'kinds', 'of', 'statistics.')


In [85]:
mach = a+b+c+d+e+f

In [86]:
print(mach)

Therearethreekindsofstatistics.


In [87]:
print('mach')

mach


In [88]:
print(a, b, c, d, e, f)

There are three kinds of statistics.


In [89]:
mach2=(a, b, c, d, e, f)

In [90]:
print(mach2)

('There', 'are', 'three', 'kinds', 'of', 'statistics.')


In [1]:
lakes= make_array("Erie", "Huron", "Michigan", "Ontario", "Superior")

NameError: name 'make_array' is not defined

In [2]:
mach2

NameError: name 'mach2' is not defined

In [3]:
import numpy as np


In [4]:
lakes = make_array("Erie", "Huron", "Michigan", "Ontario", "Superior")

NameError: name 'make_array' is not defined

In [5]:
print(mach2)

NameError: name 'mach2' is not defined

In [6]:
mystring1 = 'There are three kinds of lies: lies, damned lies, and statistics.' 
mystring1.split(',')

['There are three kinds of lies: lies', ' damned lies', ' and statistics.']

In [7]:
mystring1.split()

['There',
 'are',
 'three',
 'kinds',
 'of',
 'lies:',
 'lies,',
 'damned',
 'lies,',
 'and',
 'statistics.']

In [8]:
a=mystring1.split()[0]
b=mystring1.split()[1]
c=mystring1.split()[2]
d=mystring1.split()[3]
e=mystring1.split()[4]
f=mystring1.split()[10]

In [9]:
mach2=a+" "+b+" "+c+" "+d+" "+e+" "+f

In [10]:
print(mach2)

There are three kinds of statistics.


In [11]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")

NameError: name 'make_array' is not defined

In [12]:
import numpy as np

In [13]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")

NameError: name 'make_array' is not defined

In [14]:
english_parts_of_speech=np.array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")

TypeError: array() takes from 1 to 2 positional arguments but 8 were given

In [15]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_context("talk")

In [16]:
import numpy as np

In [17]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")

NameError: name 'make_array' is not defined

In [18]:
import numpy as np

In [19]:
array = np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [20]:
array = np.array(["noun", "pronoun", "verb"])

In [21]:
array

array(['noun', 'pronoun', 'verb'], dtype='<U7')

In [22]:
lakes= make_array([])

NameError: name 'make_array' is not defined

In [23]:
lakes = make_array(["Erie", "Huron", "Michigan", "Ontario", "Superior"])

NameError: name 'make_array' is not defined

In [24]:
lakes = np.array(["Erie", "Huron", "Michigan", "Ontario", "Superior"])

In [25]:
lakes

array(['Erie', 'Huron', 'Michigan', 'Ontario', 'Superior'], dtype='<U8')

In [26]:
lakes[0]

'Erie'

In [27]:
all_five=lakes[1],lakes[2]

In [28]:
all_five

('Huron', 'Michigan')

In [29]:
type(all_five)

tuple

In [30]:
np.sum(lakes)

TypeError: cannot perform reduce with flexible type

In [31]:
lakes

array(['Erie', 'Huron', 'Michigan', 'Ontario', 'Superior'], dtype='<U8')

In [32]:
print(lakes)

['Erie' 'Huron' 'Michigan' 'Ontario' 'Superior']


In [33]:
type(lakes)

numpy.ndarray

In [34]:
test = lakes[0]+","+lakes[1]

In [35]:
test

'Erie,Huron'

In [36]:
type[test]

TypeError: 'type' object is not subscriptable

In [37]:
type(test)

str

In [38]:
"*".join(["One", "Two", "Three", "Four", "Five"])

'One*Two*Three*Four*Five'

In [39]:
" AND ".join(["One", "Two", "Three", "Four", "Five"])

'One AND Two AND Three AND Four AND Five'

In [40]:
book_title_words = np.array(["Eats", "Shoots", "and Leaves"])

In [41]:
book_title_words

array(['Eats', 'Shoots', 'and Leaves'], dtype='<U10')

In [42]:
with_commas = ",".join(book_title_words)

In [43]:
with_commas

'Eats,Shoots,and Leaves'

In [44]:
without_commas = " ".join(book_title_words)

In [45]:
without_commas

'Eats Shoots and Leaves'

In [46]:
book_title_words = np.array(["Eats", "Shoots", "and Leaves"])
with_commas = ",".join(book_title_words)
without_commas = " ".join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats,Shoots,and Leaves
without_commas: Eats Shoots and Leaves


In [48]:
lake_elevations = np.array([571, 577, 577, 246, 600])  # Note these are in alphabetical order, E H M O S 
# The fourth element is the elevation of Lake Ontario
lake_ontario_feet = lake_elevations[3]
lake_ontario_meters = lake_ontario_feet * 0.3048

In [49]:
lake_ontario_feet

246

In [50]:
lake_ontario_meters

74.9808

In [51]:
lake_elevations

array([571, 577, 577, 246, 600])

In [52]:
lake_elevations*2

array([1142, 1154, 1154,  492, 1200])

In [53]:
print(lake_elevations*2)

[1142 1154 1154  492 1200]


In [54]:
lake_latitudes = np.array([42.1, 45.0, 43.4, 43.6, 47.7])

In [55]:
math.cos(45)

NameError: name 'math' is not defined

In [56]:
np.cos(90)

-0.4480736161291701

In [57]:
np.cos(3.1415926)

-0.9999999999999986

In [58]:
lake_latitudes = np.array([42.1, 45.0, 43.4, 43.6, 47.7])

In [60]:
np.cos(np.pi*lake_latitudes/180)

array([0.74197584, 0.70710678, 0.72657467, 0.72417186, 0.67301251])

In [61]:
# read the data into a table
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]
# this shows the first 4 rows of the table
temptimeseries.head(4)

NameError: name 'pd' is not defined

In [62]:
import pandas as pd

In [63]:
# read the data into a table
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]
# this shows the first 4 rows of the table
temptimeseries.head(4)

FileNotFoundError: [Errno 2] No such file or directory: 'Weather-MDW-2020.csv'

In [64]:
test = np.array(10,8,4,1)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [65]:
test = np.array([10,8,4,1])

In [66]:
test

array([10,  8,  4,  1])

In [67]:
np.diff(test)

array([-2, -4, -3])

In [68]:
test = np.array([23,46,12,19])

In [69]:
two = np.diff(test)

In [70]:
two

array([ 23, -34,   7])

In [71]:
np.max(two)

23

In [72]:
np.min(two)

-34

In [73]:
# read the data into a table
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]
# this shows the first 4 rows of the table
temptimeseries.head(4)

FileNotFoundError: [Errno 2] No such file or directory: 'Weather-MDW-2020.csv'

In [74]:
import warnings
warnings.simplefilter('ignore', FutureWarning)

In [75]:
# read the data into a table
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]
# this shows the first 4 rows of the table
temptimeseries.head(4)

FileNotFoundError: [Errno 2] No such file or directory: 'Weather-MDW-2020.csv'

In [76]:
test

array([23, 46, 12, 19])

In [77]:
np.cumsum(test[3])

array([19])

In [78]:
np.cumsum(test)

array([ 23,  69,  81, 100])

In [79]:
np.cumsum(test.2)

SyntaxError: invalid syntax (<ipython-input-79-324d1fcdc8af>, line 1)

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], index = [1,2,3], columns = ["a", "b", "c"])

a  b  c
1  1  2  3
2  4  5  6
3  7  8  9

In [4]:
log(10)

NameError: name 'log' is not defined

In [5]:
math.log(10)

NameError: name 'math' is not defined

In [6]:
np.log(10)

2.302585092994046

In [7]:
lol=[[1,2,3], [4,5,6], [7,8,9]]

In [8]:
arr=np.array(lol)

In [9]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
lol[1]

[4, 5, 6]

In [11]:
lol[1][1]

5

In [12]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [13]:
lol[0]

[1, 2, 3]

In [14]:
type(lol[0][0])

int

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [18]:
np.float(arr)

<ipython-input-18-77df89a2cc1f>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(arr)


TypeError: only size-1 arrays can be converted to Python scalars

In [20]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [21]:
minarddata

NameError: name 'minarddata' is not defined

In [22]:
fruits = ["apple", "banana", "cherry", "durian"]

In [23]:
fruits[1]

'banana'

In [24]:
fruits[1:3]

['banana', 'cherry']

In [25]:
fruits[::2]

['apple', 'cherry']

In [26]:
fruits.append(5)

In [27]:
fruits

['apple', 'banana', 'cherry', 'durian', 5]

In [28]:
array = np.array([1,2,3,4])

In [29]:
print(array)

[1 2 3 4]


In [30]:
array[2]

3

In [31]:
array[2:]

array([3, 4])

In [32]:
array[::2]

array([1, 3])

In [33]:
array_complex = array.astype(np.complex)

<ipython-input-33-6b4909351a11>:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_complex = array.astype(np.complex)


In [34]:
np.complex

<ipython-input-34-087dad13a955>:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex


complex

In [35]:
len(array)

4

In [36]:
array2 = np.array([5,6,7,8])

In [37]:
barray = array + array2

In [38]:
np.concatenate(array, array2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [39]:
np.concatenate((array, array2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
print(np.arange(4,10))

[4 5 6 7 8 9]


In [41]:
dict = {'a': [1,2,3], 'b': [4,5,6], 'c': [7,8,9]}

In [42]:
dict

{'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}

In [43]:
df1 = pd.DataFrame(dict, index = [1,2,3])

In [44]:
print(df1)

   a  b  c
1  1  4  7
2  2  5  8
3  3  6  9


In [45]:
df2 = pd.DataFrame(dict, column = [1,2,3])

TypeError: __init__() got an unexpected keyword argument 'column'

In [46]:
df2 = pd.DataFrame(dict, columns = [1,2,3])

In [47]:
print(df2)

Empty DataFrame
Columns: [1, 2, 3]
Index: []


In [1]:
mystring1 = 'There are three kinds of lies: lies, damned lies, and statistics.' 

In [2]:
mystring1.split(',')

['There are three kinds of lies: lies', ' damned lies', ' and statistics.']

In [3]:
mystring1.split(',')[2]

' and statistics.'

In [4]:
mystring1.split()
a=mystring1.split()[0]
b=mystring1.split()[1]
c=mystring1.split()[2]
d=mystring1.split()[3]
e=mystring1.split()[4]
f=mystring1.split()[10]
mach2=a+" "+b+" "+c+" "+d+" "+e+" "+f

In [5]:
mach2

'There are three kinds of statistics.'

In [6]:
book_title_words = np.array(["Eats", "Shoots", "and Leaves"])
with_commas = ", ".join(book_title_words)
without_commas = " ".join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

NameError: name 'np' is not defined

In [7]:
book_title_words = np.array(["Eats", "Shoots", "and Leaves"])
with_commas = ", ".join(book_title_words)
without_commas = " ".join(book_title_words)

NameError: name 'np' is not defined

In [8]:
import numpy as np

In [9]:
book_title_words = np.array(["Eats", "Shoots", "and Leaves"])
with_commas = ", ".join(book_title_words)
without_commas = " ".join(book_title_words)

In [10]:
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats, Shoots, and Leaves
without_commas: Eats Shoots and Leaves


In [11]:
lake_latitudes = np.array([42.1, 45.0, 43.4, 43.6, 47.7])
cosine_latitudes = np.cos(np.pi*lake_latitudes/180)
print(cosine_latitudes)

[0.74197584 0.70710678 0.72657467 0.72417186 0.67301251]


In [12]:
# read the data into a table
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]
# this shows the first 4 rows of the table
temptimeseries.head(4)

NameError: name 'pd' is not defined

In [13]:
import pandas as pd

In [14]:
# read the data into a table
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]
# this shows the first 4 rows of the table
temptimeseries.head(4)

FileNotFoundError: [Errno 2] No such file or directory: 'Weather-MDW-2020.csv'

In [15]:
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]

FileNotFoundError: [Errno 2] No such file or directory: 'Weather-MDW-2020.csv'

In [16]:
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]

In [17]:
temptimeseries.head(4)

DATE  TMIN  PRCP
0  2020-01-01    22  0.00
1  2020-01-02    37  0.00
2  2020-01-03    35  0.00
3  2020-01-04    27  0.01

In [18]:
tmin = temptimeseries.TMIN.values
tmin

array([22, 37, 35, 27, 25, 26, 28, 17, 23, 39, 26, 25, 32, 29, 29, 17, 17,
        6,  3, 18, 17, 24, 30, 34, 33, 28, 28, 31, 30, 31, 31, 33, 35, 30,
       31, 27, 27, 22, 26, 23, 27, 25, 24,  5, -1,  7, 18, 29, 26, 17, 11,
       12, 26, 33, 38, 32, 26, 22, 18, 16, 30, 35, 32, 35, 33, 28, 23, 40,
       47, 34, 36, 36, 34, 32, 34, 32, 37, 39, 40, 31, 27, 28, 33, 33, 32,
       38, 37, 45, 44, 39, 37, 36, 31, 46, 36, 37, 36, 55, 49, 36, 34, 42,
       49, 35, 30, 28, 28, 33, 33, 40, 36, 37, 40, 44, 42, 42, 43, 39, 53,
       42, 42, 37, 58, 48, 41, 42, 38, 46, 34, 31, 37, 40, 39, 45, 55, 57,
       52, 54, 52, 52, 55, 56, 57, 55, 64, 70, 70, 72, 65, 58, 55, 52, 55,
       67, 70, 68, 72, 61, 59, 65, 74, 62, 59, 57, 54, 57, 55, 59, 65, 64,
       69, 71, 70, 66, 63, 61, 63, 70, 72, 72, 72, 73, 74, 72, 69, 72, 73,
       76, 75, 75, 72, 70, 70, 67, 64, 67, 68, 69, 68, 76, 71, 67, 73, 72,
       65, 66, 69, 75, 72, 69, 72, 72, 70, 65, 65, 65, 59, 57, 65, 62, 67,
       72, 69, 66, 63, 70

In [19]:
test=np.diff(tmin)
largest_temp_change = np.max(test)
smallest_temp_change = np.min(test)

In [20]:
largest_temp_change

21

In [21]:
smallest_temp_change

-19

In [22]:
np.cumsum(temptimeseries.PRCP)

0       0.00
1       0.00
2       0.00
3       0.01
4       0.01
       ...  
361    36.02
362    36.02
363    36.25
364    36.46
365    36.46
Name: PRCP, Length: 366, dtype: float64

In [23]:
multiples_of_99 = np.arrange(0, 9999, 99)
multiples_of_99

AttributeError: module 'numpy' has no attribute 'arrange'

In [25]:
multiples_of_99 = np.arange(0, 9999+99, 99)
multiples_of_99

array([   0,   99,  198,  297,  396,  495,  594,  693,  792,  891,  990,
       1089, 1188, 1287, 1386, 1485, 1584, 1683, 1782, 1881, 1980, 2079,
       2178, 2277, 2376, 2475, 2574, 2673, 2772, 2871, 2970, 3069, 3168,
       3267, 3366, 3465, 3564, 3663, 3762, 3861, 3960, 4059, 4158, 4257,
       4356, 4455, 4554, 4653, 4752, 4851, 4950, 5049, 5148, 5247, 5346,
       5445, 5544, 5643, 5742, 5841, 5940, 6039, 6138, 6237, 6336, 6435,
       6534, 6633, 6732, 6831, 6930, 7029, 7128, 7227, 7326, 7425, 7524,
       7623, 7722, 7821, 7920, 8019, 8118, 8217, 8316, 8415, 8514, 8613,
       8712, 8811, 8910, 9009, 9108, 9207, 9306, 9405, 9504, 9603, 9702,
       9801, 9900, 9999])

In [26]:
import pandas as pd

population = pd.read_csv("world_population.csv")['Population'].values
population

FileNotFoundError: [Errno 2] No such file or directory: 'world_population.csv'

In [27]:
restaurant_bills = np.array([20.12, 39.90, 31.01])
print("Restaurant bills:\t", restaurant_bills)
tips = .2 * restaurant_bills
print("Tips:\t\t\t", tips)

Restaurant bills:	 [20.12 39.9  31.01]
Tips:			 [4.024 7.98  6.202]


In [28]:
total = restaurant_bills + tips

In [29]:
print(total)

[24.144 47.88  37.212]


In [30]:
np.sum(total)

109.236

In [31]:
np.arange(0,2**x,10)

NameError: name 'x' is not defined

In [32]:
np.arange(0,29,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [34]:
power_of_two = np.arange(0,30,1)

In [35]:
2**power_of_two

array([        1,         2,         4,         8,        16,        32,
              64,       128,       256,       512,      1024,      2048,
            4096,      8192,     16384,     32768,     65536,    131072,
          262144,    524288,   1048576,   2097152,   4194304,   8388608,
        16777216,  33554432,  67108864, 134217728, 268435456, 536870912])

In [36]:
top_10_movie_ratings = np.array([9.2, 9.2, 9., 8.9, 8.9, 8.9, 8.9, 8.9, 8.9, 8.8])
top_10_movie_names = np.array([
        'The Shawshank Redemption (1994)',
        'The Godfather (1972)',
        'The Godfather: Part II (1974)',
        'Pulp Fiction (1994)',
        "Schindler's List (1993)",
        'The Lord of the Rings: The Return of the King (2003)',
        '12 Angry Men (1957)',
        'The Dark Knight (2008)',
        'Il buono, il brutto, il cattivo (1966)',
        'The Lord of the Rings: The Fellowship of the Ring (2001)'])

top_10_movies = pd.DataFrame({
    'Rating': top_10_movie_ratings
    'Name': top_10_movie_names
})
# We've put this next line here so your table will get printed out when you
# run this cell.
top_10_movies

SyntaxError: invalid syntax (<ipython-input-36-7a4e11b26412>, line 16)

In [37]:
top_10_movie_ratings = np.array([9.2, 9.2, 9., 8.9, 8.9, 8.9, 8.9, 8.9, 8.9, 8.8])
top_10_movie_names = np.array([
        'The Shawshank Redemption (1994)',
        'The Godfather (1972)',
        'The Godfather: Part II (1974)',
        'Pulp Fiction (1994)',
        "Schindler's List (1993)",
        'The Lord of the Rings: The Return of the King (2003)',
        '12 Angry Men (1957)',
        'The Dark Knight (2008)',
        'Il buono, il brutto, il cattivo (1966)',
        'The Lord of the Rings: The Fellowship of the Ring (2001)'])

In [39]:
top_10_movies = pd.DataFrame({
    'Rating': top_10_movie_ratings,
    'Name': top_10_movie_names
})

In [40]:
top_10_movies

Rating                                               Name
0     9.2                    The Shawshank Redemption (1994)
1     9.2                               The Godfather (1972)
2     9.0                      The Godfather: Part II (1974)
3     8.9                                Pulp Fiction (1994)
4     8.9                            Schindler's List (1993)
5     8.9  The Lord of the Rings: The Return of the King ...
6     8.9                                12 Angry Men (1957)
7     8.9                             The Dark Knight (2008)
8     8.9             Il buono, il brutto, il cattivo (1966)
9     8.8  The Lord of the Rings: The Fellowship of the R...

In [41]:
imdb = pd.read_csv("imdb.csv")

In [42]:
highest_rating = np.max(imdb['Rating'].values)
highest_rating

9.2

In [43]:
imdb.sort_values("Rating", ascending=False)

Votes  Rating                                   Title  Year  Decade
22   1027398     9.2                           The Godfather  1972    1970
53   1498733     9.2                The Shawshank Redemption  1994    1990
91    692753     9.0                  The Godfather: Part II  1974    1970
105   384187     8.9                            12 Angry Men  1957    1950
57    447875     8.9  Il buono, il brutto, il cattivo (1966)  1966    1960
..       ...     ...                                     ...   ...     ...
168   500576     8.0                   Monsters, Inc. (2001)  2001    2000
166    59578     8.0                           The Big Sleep  1946    1940
46    427099     8.0              X-Men: Days of Future Past  2014    2010
51     87437     8.0                           Roman Holiday  1953    1950
125    26012     8.0                             Kumonosu-jô  1957    1950

[250 rows x 5 columns]

In [44]:
imdb_by_year = imbd.sort_values("Year")
imdb_by_year

NameError: name 'imbd' is not defined

In [45]:
imdb_by_year = imdb.sort_values("Year")
imdb_by_year

Votes  Rating                     Title  Year  Decade
173   55784     8.3                   The Kid  1921    1920
205   58506     8.2             The Gold Rush  1925    1920
146   46332     8.2               The General  1926    1920
49    98794     8.3                Metropolis  1927    1920
0     88355     8.4                         M  1931    1930
..      ...     ...                       ...   ...     ...
100  369141     8.1  The Grand Budapest Hotel  2014    2010
9     46987     8.0          Relatos salvajes  2014    2010
70   689541     8.6              Interstellar  2014    2010
233  262425     8.3        Mad Max: Fury Road  2015    2010
41    79615     8.5       Inside Out (2015/I)  2015    2010

[250 rows x 5 columns]

In [46]:
imdb_by_year[0]

KeyError: 0

In [47]:
imdb_by_year["Title"].values[0]

'The Kid'

In [48]:
forties = imdb.loc[imdb.Decade == 1940]

In [49]:
forties

Votes  Rating                             Title  Year  Decade
21    55793     8.1               The Grapes of Wrath  1940    1940
50    86715     8.3                  Double Indemnity  1944    1940
72   101754     8.1                The Maltese Falcon  1941    1940
75    71003     8.3  The Treasure of the Sierra Madre  1948    1940
102   35983     8.1       The Best Years of Our Lives  1946    1940
118   81887     8.3               Ladri di biciclette  1948    1940
120   66622     8.0                         Notorious  1946    1940
158  350551     8.5                        Casablanca  1942    1940
166   59578     8.0                     The Big Sleep  1946    1940
167   78216     8.2                           Rebecca  1940    1940
213  242353     8.6             It's a Wonderful Life  1946    1940
215  101785     8.3                     The Third Man  1949    1940
240  117590     8.4                The Great Dictator  1940    1940
243  268905     8.4                      Citizen Kane  1941    1940

In [50]:
np.average(forties)

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [51]:
np.average(forties.Rating)

8.257142857142856

In [52]:
imdb.loc[imdb.Year == 1999]

Votes  Rating            Title  Year  Decade
87   1177098     8.8       Fight Club  1999    1990
104   735056     8.4  American Beauty  1999    1990
115   630994     8.1  The Sixth Sense  1999    1990
129  1073043     8.7       The Matrix  1999    1990
149   672878     8.5   The Green Mile  1999    1990

In [53]:
imdb.loc[imdb.Rating > 8.5]

Votes  Rating                                              Title  Year  \
3     635139     8.6                                               Léon  1994   
22   1027398     9.2                                      The Godfather  1972   
47    767224     8.6                           The Silence of the Lambs  1991   
53   1498733     9.2                           The Shawshank Redemption  1994   
57    447875     8.9             Il buono, il brutto, il cattivo (1966)  1966   
68    967389     8.7              The Lord of the Rings: The Two Towers  2002   
70    689541     8.6                                       Interstellar  2014   
76   1473049     8.9                                    The Dark Knight  2008   
78    192206     8.6                            C'era una volta il West  1968   
81   1271949     8.7                                          Inception  2010   
87   1177098     8.8                                         Fight Club  1999   
91    692753     9.0                             The Godfather: Part II  1974   
96    656756     8.6                                 The Usual Suspects  1995   
98    206216     8.7                               Shichinin no samurai  1954   
103   644556     8.7                                         Goodfellas  1990   
105   384187     8.9                                       12 Angry Men  1957   
129  1073043     8.7                                         The Matrix  1999   
141  1074146     8.9      The Lord of the Rings: The Return of the King  2003   
147   761224     8.9                                   Schindler's List  1993   
156   700283     8.7     Star Wars: Episode V - The Empire Strikes Back  1980   
169   895411     8.6                                              Se7en  1995   
178  1099087     8.8  The Lord of the Rings: The Fellowship of the Ring  2001   
189   770011     8.7                                          Star Wars  1977   
204   358305     8.6                                    La vita è bella  1997   
213   242353     8.6                              It's a Wonderful Life  1946   
223   606395     8.7                    One Flew Over the Cuckoo's Nest  1975   
224  1166532     8.9                                       Pulp Fiction  1994   
242   476501     8.6                                     Cidade de Deus  2002   
245  1078416     8.7                                       Forrest Gump  1994   

     Decade  
3      1990  
22     1970  
47     1990  
53     1990  
57     1960  
68     2000  
70     2010  
76     2000  
78     1960  
81     2010  
87     1990  
91     1970  
96     1990  
98     1950  
103    1990  
105    1950  
129    1990  
141    2000  
147    1990  
156    1980  
169    1990  
178    2000  
189    1970  
204    1990  
213    1940  
223    1970  
224    1990  
242    2000  
245    1990

In [54]:
average_20th_century_rating = np.average(imdb.loc[imdb.Year < 1999])
average_21st_century_rating = np.average(imdb.loc[imdb.Year > 1999])
print("Average 20th century rating:", average_20th_century_rating)
print("Average 21st century rating:", average_21st_century_rating)

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [55]:
np.average(imdb.loc[imdb.Year < 1999].Rating)

8.271686746987951

In [56]:
average_21st_century_rating = np.average(imdb.loc[imdb.Year > 1999].Rating)

In [57]:
np.average(imdb.loc[imdb.Year > 1999].Rating)

8.237974683544303

In [58]:
np.average(imdb.loc[imdb.Decade < 2000].Rating)

8.278362573099415

In [59]:
imdb.shape[0]

250

In [60]:
imdb.loc[imdb.Year % 2 == 0].shape[0]num_even_year_movies = imdb.loc[imdb.Year % 2 == 0].shape[0]
num_even_year_movies

127

In [61]:
num_even_year_movies = imdb.loc[imdb.Year % 2 == 0].shape[0]
num_even_year_movies

127

In [62]:
num_even_year_movies

127

In [63]:
imdb.loc[imdb.Year % 2 == 0].shape[0]

127

In [64]:
imdb.loc[imdb.Population >= 6000000000].shape[0]

AttributeError: 'DataFrame' object has no attribute 'Population'

In [70]:
farmers_markets = pd.read_csv("farmers_markets.csv")

In [67]:
farmers_markets.shape[0]

NameError: name 'farmers_markets' is not defined

In [68]:
farmers_markets.shape[1]

NameError: name 'farmers_markets' is not defined

In [69]:
farmers_markets_locations = farmers_markets[["MarketName", "City", "State", "Latitude", "Longitude"]]
farmers_markets_locations

NameError: name 'farmers_markets' is not defined

In [71]:
farmers_markets_locations = farmers_markets[["MarketName", "City", "State", "Latitude", "Longitude"]]
farmers_markets_locations

KeyError: "['City', 'Longitude', 'Latitude'] not in index"

In [72]:
farmers_markets = pd.read_csv("farmers_markets.csv")

In [73]:
farmers_markets

FMID                                        MarketName  \
0     1012063   Caledonia Farmers Market Association - Danville   
1     1011871                 Stearns Homestead Farmers' Market   
2     1011878                                   100 Mile Market   
3     1009364                 106 S. Main Street Farmers Market   
4     1010691               10th Steet Community Farmers Market   
...       ...                                               ...   
8541  1004767                    Zia Bernalillo Farmers' Market   
8542  1000778                          Zimmerman Farmers Market   
8543  1002868                        Zion Canyon Farmers Market   
8544  1004686                         Zionsville Farmers Market   
8545  1011418                         Zona Rosa Farmers' Market   

                                                Website  \
0     https://sites.google.com/site/caledoniafarmers...   
1                           http://Stearnshomestead.com   
2                             http://www.pfcmarkets.com   
3                http://thetownofsixmile.wordpress.com/   
4                                                   NaN   
...                                                 ...   
8541                         http://www.eatfreshnm.org/   
8542                     http://www.pzfarmersmarket.org   
8543                         http://www.zionharvest.org   
8544             http://www.zionsvillefarmersmarket.org   
8545                                                NaN   

                                               Facebook Twitter Youtube  \
0     https://www.facebook.com/Danville.VT.Farmers.M...     NaN     NaN   
1                                                   NaN     NaN     NaN   
2       https://www.facebook.com/100MileMarket/?fref=ts     NaN     NaN   
3                                                   NaN     NaN     NaN   
4                                                   NaN     NaN     NaN   
...                                                 ...     ...     ...   
8541   https://www.facebook.com/farmersmarketsnm?ref=hl     NaN     NaN   
8542                  princeton-zimerman farmers market     NaN     NaN   
8543  https://www.facebook.com/ZionCanyonFarmersMark...     NaN     NaN   
8544                                                NaN     NaN     NaN   
8545                                                NaN     NaN     NaN   

                                             OtherMedia  \
0                                                   NaN   
1                                                   NaN   
2              https://www.instagram.com/100milemarket/   
3                                                   NaN   
4     http://agrimissouri.com/mo-grown/grodetail.php...   
...                                                 ...   
8541                                                NaN   
8542                                                NaN   
8543                                                NaN   
8544                                                NaN   
8545                                                NaN   

                          street         city      County  ... Coffee Beans  \
0                            NaN    Danville    Caledonia  ...      Y     Y   
1                6975 Ridge Road       Parma     Cuyahoga  ...      N     N   
2                507 Harrison St    Kalamazoo   Kalamazoo  ...      N     N   
3             106 S. Main Street     Six Mile         NaN  ...      N     N   
4         10th Street and Poplar       Lamar       Barton  ...      N     N   
...                          ...          ...         ...  ...    ...   ...   
8541    335 S. Camino del Pueblo   Bernalillo    Sandoval  ...      N     Y   
8542    Lions Park, Main Street     Zimmerman   Sherburne  ...      N     N   
8543        1212 Zion Park Blvd.   Springdale  Washington  ...      Y     N   
8544     Hawthorne & Main Street   Zionsville       Boone  ...      N     N   
8545  Off of I-2

In [74]:
num_farmers_markets_columns = farmers_markets.shape[1]
print("The table has", num_farmers_markets_columns, "columns in it!")

The table has 59 columns in it!


In [75]:
farmers_markets_locations = farmers_markets[["MarketName", "city", "State", "y", "x"]]
farmers_markets_locations

KeyError: "['City', 'Longitude', 'Latitude'] not in index"

In [76]:
farmers_markets_locations = farmers_markets[["MarketName", "city", "State", "y", "x"]]
farmers_markets_locations

MarketName         city  \
0      Caledonia Farmers Market Association - Danville    Danville    
1                    Stearns Homestead Farmers' Market       Parma    
2                                      100 Mile Market    Kalamazoo   
3                    106 S. Main Street Farmers Market     Six Mile   
4                  10th Steet Community Farmers Market       Lamar    
...                                                ...          ...   
8541                    Zia Bernalillo Farmers' Market   Bernalillo   
8542                          Zimmerman Farmers Market    Zimmerman   
8543                        Zion Canyon Farmers Market   Springdale   
8544                         Zionsville Farmers Market   Zionsville   
8545                         Zona Rosa Farmers' Market  Kansas City   

               State          y           x  
0            Vermont  44.411013  -72.140305  
1               Ohio  41.375118  -81.728597  
2           Michigan  42.296024  -85.574887  
3     South Carolina  34.804200  -82.818700  
4           Missouri  37.495628  -94.274619  
...              ...        ...         ...  
8541      New Mexico  35.313704 -106.546840  
8542       Minnesota  45.437700  -93.585014  
8543            Utah  37.184508 -113.003311  
8544         Indiana  39.949100  -86.261200  
8545        Missouri  39.246317  -94.580864  

[8546 rows x 5 columns]

In [77]:
farmers_markets_without_fmid = farmers_markets.drop(columns=["FMID", "updateTime"])
farmers_markets_without_fmid

MarketName  \
0      Caledonia Farmers Market Association - Danville   
1                    Stearns Homestead Farmers' Market   
2                                      100 Mile Market   
3                    106 S. Main Street Farmers Market   
4                  10th Steet Community Farmers Market   
...                                                ...   
8541                    Zia Bernalillo Farmers' Market   
8542                          Zimmerman Farmers Market   
8543                        Zion Canyon Farmers Market   
8544                         Zionsville Farmers Market   
8545                         Zona Rosa Farmers' Market   

                                                Website  \
0     https://sites.google.com/site/caledoniafarmers...   
1                           http://Stearnshomestead.com   
2                             http://www.pfcmarkets.com   
3                http://thetownofsixmile.wordpress.com/   
4                                                   NaN   
...                                                 ...   
8541                         http://www.eatfreshnm.org/   
8542                     http://www.pzfarmersmarket.org   
8543                         http://www.zionharvest.org   
8544             http://www.zionsvillefarmersmarket.org   
8545                                                NaN   

                                               Facebook Twitter Youtube  \
0     https://www.facebook.com/Danville.VT.Farmers.M...     NaN     NaN   
1                                                   NaN     NaN     NaN   
2       https://www.facebook.com/100MileMarket/?fref=ts     NaN     NaN   
3                                                   NaN     NaN     NaN   
4                                                   NaN     NaN     NaN   
...                                                 ...     ...     ...   
8541   https://www.facebook.com/farmersmarketsnm?ref=hl     NaN     NaN   
8542                  princeton-zimerman farmers market     NaN     NaN   
8543  https://www.facebook.com/ZionCanyonFarmersMark...     NaN     NaN   
8544                                                NaN     NaN     NaN   
8545                                                NaN     NaN     NaN   

                                             OtherMedia  \
0                                                   NaN   
1                                                   NaN   
2              https://www.instagram.com/100milemarket/   
3                                                   NaN   
4     http://agrimissouri.com/mo-grown/grodetail.php...   
...                                                 ...   
8541                                                NaN   
8542                                                NaN   
8543                                                NaN   
8544                                                NaN   
8545                                                NaN   

                          street         city      County           State  \
0                            NaN    Danville    Caledonia         Vermont   
1                6975 Ridge Road       Parma     Cuyahoga            Ohio   
2                507 Harrison St    Kalamazoo   Kalamazoo        Michigan   
3             106 S. Main Street     Six Mile         NaN  South Carolina   
4         10th Street and Poplar       Lamar       Barton        Missouri   
...                          ...          ...         ...             ...   
8541    335 S. Camino del Pueblo   Bernalillo    Sandoval      New Mexico   
8542    Lions Park, Main Street     Zimmerman   Sherburne       Minnesota   
8543        1212 Zion Park Blvd.   Springdale  Washington            Utah   
8544     Hawthorne & Main Street   Zionsville       Boone         Indiana   
8545  Off of I-29 and Barry Road  Kansas City      Platte        Missouri   

      ... Wine Coffee Beans Fruits Grains Juices Mushrooms PetFood Tofu  \
0     ...    N      Y     Y 

In [78]:
northern_markets = farmers_markets_locations.sort_values('y', ascending = False).iloc[:5]
northern_markets

MarketName            city   State          y  \
7274   Tanana Valley Farmers Market       Fairbanks  Alaska  64.862750   
2392         Ester Community Market           Ester  Alaska  64.845900   
2430      Fairbanks Downtown Market       Fairbanks  Alaska  64.844414   
5182         Nenana Open Air Market          Nenana  Alaska  64.556600   
3496  Highway's End Farmers' Market  Delta Junction  Alaska  64.038462   

               x  
7274 -147.781100  
2392 -148.010000  
2430 -147.719593  
5182 -149.096000  
3496 -145.733115

In [79]:
chicago_markets = farmers_markets_locations.loc[farmers_markets_locations.city == "Chicago"]
chicago_markets

MarketName     city     State  \
39                           61st Street Farmers Market  Chicago  Illinois   
193                        Andersonville Farmers Market  Chicago  Illinois   
267                    Ashburn (Chicago) Farmers Market  Chicago  Illinois   
343                     Austin (Chicago) Farmers Market  Chicago  Illinois   
795                Bronzeville (Chicago) Farmers Market  Chicago  Illinois   
1205                   Chatham (Chicago) Farmers Market  Chicago  Illinois   
1258                  Chicago Nettlehorst French Market  Chicago  Illinois   
1557                              Conuco Farmers Market  Chicago  Illinois   
1694                          Crisp! Catholic Charities  Chicago  Illinois   
1695                       Crisp! Mobile Farmers Market  Chicago  Illinois   
1762                 Daley Plaza Chicago Farmers Market  Chicago  Illinois   
1871                            Devon Community Market   Chicago  Illinois   
1895             Division Street Chicago Farmers Market  Chicago  Illinois   
2310  Eli's Cheesecake and Wright College Farmer's M...  Chicago  Illinois   
2367                           Englewood Farmers Market  Chicago  Illinois   
2380                         Erie Street Farmers Market  Chicago  Illinois   
2454  Faith in Place Winter Farmers Market - Augusta...  Chicago  Illinois   
2456  Faith in Place Winter Farmers Market - Beverly...  Chicago  Illinois   
2468  Faith in Place Winter Farmers Market - St. Ste...  Chicago  Illinois   
2469  Faith in Place Winter Farmers Market - Temple ...  Chicago  Illinois   
2498                  Farmer Fridays at Uncommon Ground  Chicago  Illinois   
2617                                 Farmstand at CHSAS  Chicago  Illinois   
2638             Federal Plaza (Chicago) Farmers Market  Chicago  Illinois   
2923             Garfield Park (Chicago) Farmers Market  Chicago  Illinois   
2929            Gately/Pullman (Chicago) Farmers Market  Chicago  Illinois   
3011                             Glenwood Sunday Market  Chicago  Illinois   
3139                         Green City Market - Indoor  Chicago  Illinois   
3140                        Green City Market - Outdoor  Chicago  Illinois   
3582                           Home Grown Cow - Chicago  Chicago  Illinois   
3675                 Hyde Park (Chicago) Farmers Market  Chicago  Illinois   
3692          IMAN's Fresh Beats & Eats Farmers' Market  Chicago  Illinois   
3701                   Independence Park Farmers Market  Chicago  Illinois   
4052                                  La Follette Park   Chicago  Illinois   
4179                  Lawndale (Chicago) Farmers Market  Chicago  Illinois   
4287              Lincoln Park (Chicago) Farmers Market  Chicago  Illinois   
4292              Lincoln Square Chicago Farmers Market  Chicago  Illinois   
5014               Morgan Park (Chicago) Farmers Market  Chicago  Illinois   
5314              North Center (Chicago) Farmers Market  Chicago  Illinois   
5888                      Pilsen Community Farm Market   Chicago  Illinois   
5928                      Plant Chicago Farmers Market   Chicago  Illinois   
6010                       Portage Park Farmer's Market  Chicago  Illinois   
6068             Printer's Row (Chicago) Farmers Market  Chicago  Illinois   
6077          Prudential Plaza (Chicago) Farmers Market  Chicago  Illinois   
6679                   Sears Tower Plaza Farmers Market  Chicago  Illinois   
6776                Shore Bank (Chicago) Farmers Market  Chicago  Illinois   
6887   South Chicago Farmers Market at Chief Nomo Oasis  Chicago  Illinois   
6924               South Shore (Chicago) Farmers Market  Chicago  Illinois   
6959                             Southport Green Market  Chicago  Illinois   
7638    Trinity United Church of Christ Farmer's Market  Chicago  Illinois   
7761                      Uptown Chicago Farmers Market  Chicago  Illinois   
8329      Wicker Park/Bucktown (Chicago) Farmers Market  Chicago  I

In [1]:
# read the data into a table
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]
# this shows the first 4 rows of the table
temptimeseries.head(4)

NameError: name 'pd' is not defined

In [2]:
import pandas as pd
import numpy as np

In [3]:
# read the data into a table
temptimeseries = pd.read_csv("Weather-MDW-2020.csv", delimiter=",")[["DATE", "TMIN", "PRCP"]]
# this shows the first 4 rows of the table
temptimeseries.head(4)

DATE  TMIN  PRCP
0  2020-01-01    22  0.00
1  2020-01-02    37  0.00
2  2020-01-03    35  0.00
3  2020-01-04    27  0.01

In [4]:
tmin = temptimeseries.TMIN.values
tmin

array([22, 37, 35, 27, 25, 26, 28, 17, 23, 39, 26, 25, 32, 29, 29, 17, 17,
        6,  3, 18, 17, 24, 30, 34, 33, 28, 28, 31, 30, 31, 31, 33, 35, 30,
       31, 27, 27, 22, 26, 23, 27, 25, 24,  5, -1,  7, 18, 29, 26, 17, 11,
       12, 26, 33, 38, 32, 26, 22, 18, 16, 30, 35, 32, 35, 33, 28, 23, 40,
       47, 34, 36, 36, 34, 32, 34, 32, 37, 39, 40, 31, 27, 28, 33, 33, 32,
       38, 37, 45, 44, 39, 37, 36, 31, 46, 36, 37, 36, 55, 49, 36, 34, 42,
       49, 35, 30, 28, 28, 33, 33, 40, 36, 37, 40, 44, 42, 42, 43, 39, 53,
       42, 42, 37, 58, 48, 41, 42, 38, 46, 34, 31, 37, 40, 39, 45, 55, 57,
       52, 54, 52, 52, 55, 56, 57, 55, 64, 70, 70, 72, 65, 58, 55, 52, 55,
       67, 70, 68, 72, 61, 59, 65, 74, 62, 59, 57, 54, 57, 55, 59, 65, 64,
       69, 71, 70, 66, 63, 61, 63, 70, 72, 72, 72, 73, 74, 72, 69, 72, 73,
       76, 75, 75, 72, 70, 70, 67, 64, 67, 68, 69, 68, 76, 71, 67, 73, 72,
       65, 66, 69, 75, 72, 69, 72, 72, 70, 65, 65, 65, 59, 57, 65, 62, 67,
       72, 69, 66, 63, 70

In [5]:
test=np.diff(tmin)
largest_temp_change = np.max(np.abs(test))
smallest_temp_change = np.min(np.abs(test))

In [6]:
largest_temp_change

21

In [7]:
smallest_temp_change

0